version: '3.8'

networks:
  backend:

volumes:
  db-data:
    driver: local
  kerberos-data:
    driver: local

services:
  postgres:
    image: 'postgres:15.1-alpine'
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

  kerberos-server:
    image: 'gcavalcante8808/krb5-server'
    container_name: kerberos-server
    ports:
      - "88:88"  # KDC порт
      - "749:749" # Административный порт
    volumes:
      - kerberos-data:/var/lib/krb5kdc
    environment:
      - KRB5_REALM=EXAMPLE.COM  # Указываем реалм
      - KRB5_KDC=kerberos-server  # Указываем адре
      - DOMAIN_REALM=example.com
      - KDC_PASSWORD=master_password
      - ADMIN_PASSWORD=adminpassword
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  app:
    build:
      context: .
    env_file: .env
    depends_on:
      - postgres
      - kerberos-server
    networks:
      - backend
    environment:
      - HOST=postgres:5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - KRB5_REALM=EXAMPLE.COM
      - KRB5_KDC=kerberos-server
      - KRB5_ADMIN_SERVER=kerberos-server
    ports:
      - '8080:8080'